-- =============================================
-- RENTAZT MVP — Schema Definitivo (4 tablas)
-- Ejecutar en Supabase SQL Editor
-- =============================================

-- Drop existing tables if re-running
DROP TABLE IF EXISTS whatsapp_log CASCADE;
DROP TABLE IF EXISTS rentals CASCADE;
DROP TABLE IF EXISTS inventory_items CASCADE;
DROP TABLE IF EXISTS clients CASCADE;

-- 1. Clientes
CREATE TABLE clients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  discount_rate NUMERIC DEFAULT 0, -- % descuento por defecto (ej: 0.10 = 10%)
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Inventario: Items individuales + Kits
CREATE TABLE inventory_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  daily_rate NUMERIC NOT NULL,
  category TEXT DEFAULT 'item' CHECK (category IN ('item', 'kit')),
  kit_contents JSONB, -- Para kits: [{"name":"MK 10ft","qty":4,"daily_rate":250}, ...]
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Rentas (Core)
CREATE TABLE rentals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  client_id UUID REFERENCES clients(id),
  client_name TEXT NOT NULL,
  client_phone TEXT NOT NULL,
  start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  days INT NOT NULL,
  end_date DATE NOT NULL,
  items_snapshot JSONB NOT NULL, -- [{name, qty, daily_rate, subtotal}]
  base_amount NUMERIC NOT NULL,
  shipping_cost NUMERIC DEFAULT 0,
  crew_cost NUMERIC DEFAULT 0,
  discount NUMERIC DEFAULT 0,
  final_amount NUMERIC NOT NULL,
  notes TEXT,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'returned')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Log de WhatsApp (trazabilidad)
CREATE TABLE whatsapp_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rental_id UUID REFERENCES rentals(id),
  recipient TEXT NOT NULL, -- 'owner' | 'client'
  phone TEXT NOT NULL,
  message TEXT NOT NULL,
  sent_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================
-- SEED DATA: Items reales de rigging
-- =============================================

INSERT INTO inventory_items (name, daily_rate, category) VALUES
  -- Motores
  ('Motor 1 ton', 300.00, 'item'),
  ('Motor 1/2 ton', 200.00, 'item'),
  ('Motor 1/4 ton', 150.00, 'item'),
  -- Truss
  ('MK 10ft', 250.00, 'item'),
  ('MK 5ft', 150.00, 'item'),
  ('MK 3ft', 100.00, 'item'),
  ('MK 2.5ft', 80.00, 'item'),
  -- Distribución
  ('Distro 10ch', 100.00, 'item'),
  ('Distro 12ch', 120.00, 'item'),
  ('Distro 6ch', 70.00, 'item'),
  -- Accesorios
  ('Placa', 50.00, 'item'),
  ('Shackle', 10.00, 'item'),
  ('Corner Block', 40.00, 'item'),
  ('Sleeve Block', 35.00, 'item'),
  ('Hoist Controller', 80.00, 'item'),
  -- Estructuras
  ('Ground Support 20ft', 500.00, 'item'),
  ('Ground Support 16ft', 400.00, 'item'),
  ('Base Plate', 60.00, 'item');

-- Kits pre-armados
INSERT INTO inventory_items (name, daily_rate, category, kit_contents) VALUES
  ('Kit Escenario Básico', 1800.00, 'kit',
   '[{"name":"MK 10ft","qty":4,"daily_rate":250},{"name":"Motor 1 ton","qty":4,"daily_rate":300},{"name":"Placa","qty":4,"daily_rate":50},{"name":"Shackle","qty":8,"daily_rate":10}]'::JSONB),
  ('Kit Ground Support', 2200.00, 'kit',
   '[{"name":"Ground Support 20ft","qty":2,"daily_rate":500},{"name":"MK 10ft","qty":6,"daily_rate":250},{"name":"Motor 1/2 ton","qty":4,"daily_rate":200},{"name":"Base Plate","qty":4,"daily_rate":60}]'::JSONB),
  ('Kit Iluminación', 600.00, 'kit',
   '[{"name":"Distro 12ch","qty":2,"daily_rate":120},{"name":"MK 5ft","qty":4,"daily_rate":150},{"name":"Shackle","qty":8,"daily_rate":10}]'::JSONB);

-- Clientes de ejemplo
INSERT INTO clients (name, phone, discount_rate) VALUES
  ('Rodrigo Mejia', '+525551234567', 0),
  ('Eventos Luna', '+525559876543', 0.10),
  ('Producciones Saavedra', '+525558887766', 0.05),
  ('Grupo Alfa Entretenimiento', '+525553334455', 0.15);
