/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as latamPayGatewayV2Sol from "./LatamPayGatewayV2.sol";
export type { latamPayGatewayV2Sol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mocks from "./mocks";
export type { mocks };
export type { LatamPayGateway } from "./LatamPayGateway";
