/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ILatamPayGatewayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelPayment"
      | "createPayment"
      | "isTokenSupported"
      | "pay"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PaymentCancelled"
      | "PaymentCompleted"
      | "PaymentCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelPayment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createPayment",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenSupported",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pay", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "cancelPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pay", data: BytesLike): Result;
}

export namespace PaymentCancelledEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    merchant: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: string,
    merchant: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    paymentId: string;
    merchant: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentCompletedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    payer: AddressLike,
    merchant: AddressLike,
    amountPaid: BigNumberish,
    feeCollected: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: string,
    payer: string,
    merchant: string,
    amountPaid: bigint,
    feeCollected: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    paymentId: string;
    payer: string;
    merchant: string;
    amountPaid: bigint;
    feeCollected: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentCreatedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    merchant: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: string,
    merchant: string,
    token: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    paymentId: string;
    merchant: string;
    token: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ILatamPayGateway extends BaseContract {
  connect(runner?: ContractRunner | null): ILatamPayGateway;
  waitForDeployment(): Promise<this>;

  interface: ILatamPayGatewayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelPayment: TypedContractMethod<
    [paymentId: BytesLike],
    [void],
    "nonpayable"
  >;

  createPayment: TypedContractMethod<
    [
      paymentId: BytesLike,
      merchant: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  isTokenSupported: TypedContractMethod<
    [token: AddressLike],
    [boolean],
    "view"
  >;

  pay: TypedContractMethod<[paymentId: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelPayment"
  ): TypedContractMethod<[paymentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createPayment"
  ): TypedContractMethod<
    [
      paymentId: BytesLike,
      merchant: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isTokenSupported"
  ): TypedContractMethod<[token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pay"
  ): TypedContractMethod<[paymentId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "PaymentCancelled"
  ): TypedContractEvent<
    PaymentCancelledEvent.InputTuple,
    PaymentCancelledEvent.OutputTuple,
    PaymentCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PaymentCompleted"
  ): TypedContractEvent<
    PaymentCompletedEvent.InputTuple,
    PaymentCompletedEvent.OutputTuple,
    PaymentCompletedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentCreated"
  ): TypedContractEvent<
    PaymentCreatedEvent.InputTuple,
    PaymentCreatedEvent.OutputTuple,
    PaymentCreatedEvent.OutputObject
  >;

  filters: {
    "PaymentCancelled(bytes32,address,uint256)": TypedContractEvent<
      PaymentCancelledEvent.InputTuple,
      PaymentCancelledEvent.OutputTuple,
      PaymentCancelledEvent.OutputObject
    >;
    PaymentCancelled: TypedContractEvent<
      PaymentCancelledEvent.InputTuple,
      PaymentCancelledEvent.OutputTuple,
      PaymentCancelledEvent.OutputObject
    >;

    "PaymentCompleted(bytes32,address,address,uint256,uint256,uint256)": TypedContractEvent<
      PaymentCompletedEvent.InputTuple,
      PaymentCompletedEvent.OutputTuple,
      PaymentCompletedEvent.OutputObject
    >;
    PaymentCompleted: TypedContractEvent<
      PaymentCompletedEvent.InputTuple,
      PaymentCompletedEvent.OutputTuple,
      PaymentCompletedEvent.OutputObject
    >;

    "PaymentCreated(bytes32,address,address,uint256,uint256)": TypedContractEvent<
      PaymentCreatedEvent.InputTuple,
      PaymentCreatedEvent.OutputTuple,
      PaymentCreatedEvent.OutputObject
    >;
    PaymentCreated: TypedContractEvent<
      PaymentCreatedEvent.InputTuple,
      PaymentCreatedEvent.OutputTuple,
      PaymentCreatedEvent.OutputObject
    >;
  };
}
