/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as latamPayGatewayV2Sol from "./LatamPayGatewayV2.sol";
export * as interfaces from "./interfaces";
export * as mocks from "./mocks";
export { LatamPayGateway__factory } from "./LatamPayGateway__factory";
